apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: {{CA_DATA}}
    server: {{SERVER}}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: {{NAMESPACE}}
    user: {{EMAIL}}
  name: {{USERNAME}}-context
current-context: {{USERNAME}}-context
users:
- name: {{EMAIL}}
  user:
    client-certificate-data: {{CLIENT_CERT_DATA}}
    client-key-data: {{CLIENT_KEY_DATA}}
