apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karl-cluster-viewer
subjects:
- kind: User
  name: "karl@example.com"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-viewer-karl
  apiGroup: rbac.authorization.k8s.io
