apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ming-cluster-viewer
subjects:
- kind: User
  name: "ming@example.com"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-viewer-ming
  apiGroup: rbac.authorization.k8s.io
